language: ruby
rvm:
  - 2.3.3
env:
  - TRAVIS_NODE_VERSION=7.5.0
cache:
  bundler: true
  yarn: true
  directories:
    - "app/frontend/node_modules"
bundler_args: --binstubs --without development production --jobs 3 --retry 3
services:
  - mongodb
before_install:
  - "echo 'gem: --no-document' > ~/.gemrc"
  - "gem install bundler -v '~> 1.13'"
  - "rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION"
  - "curl -o- -L https://yarnpkg.com/install.sh | bash"
  - "export PATH=$HOME/.yarn/bin:$PATH"
  - "(cd app/frontend && yarn install)"
script:
  - "bundle exec rake spec"
  - "(cd app/frontend && yarn test)"
