language: ruby
rvm: 2.3.3
env: TRAVIS_NODE_VERSION=7.5.0
cache: bundler
services:
  - mongodb
before_install:
  - "echo 'gem: --no-document' > ~/.gemrc"
  - "gem install bundler -v '~> 1.13'"
install:
  - "bundle install --binstubs --without development production --jobs 3 --retry 3"
  - "rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION"
  - "(cd app/frontend && npm install)"
script:
  - "bundle exec rake spec"
  - "(cd app/frontend && npm test)"
