language: ruby
rvm: 2.3.3
cache: bundler
bundler_args: --binstubs --without development production --jobs 3 --retry 3
services:
  - mongodb
before_install:
  - "echo 'gem: --no-document' > ~/.gemrc"
  - gem install bundler -v '~> 1.13'
before_script:
  - cp config/secrets.travis.yml config/secrets.yml
script: "bundle exec rake spec"
