default_options: &default_options
  raise_not_found_error: false

default_client_options: &default_client_options
  connect_timeout: 15

development:
  clients:
    default:
      database: o6ua6_development
      hosts:
        - localhost:27017
      options:
        <<: *default_client_options
  options:
    <<: *default_options
test:
  clients:
    default:
      database: o6ua6_test
      hosts:
        - localhost:27017
      options:
        <<: *default_client_options
        read:
          mode: :primary
        max_pool_size: 1
  options:
    <<: *default_options
production:
  clients:
    default:
      uri: <%= ENV["MONGODB_URI"] %>
      options:
        <<: *default_client_options
  options:
    <<: *default_options
